name: GitHub Pages Deployment
run-name: GitHub Pages Deployment
on:
    push:
        branches:
            - main
        paths:
            - 'github-pages-deployment/index.html'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '14'

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build
             
            - name: Deploy to Github Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./github-pages-deployment/dist
